/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.laborprojekt;

import java.util.ArrayList;
import java.util.List;
import java.util.Comparator;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 *
 * @author istsz
 */
public class GUI extends javax.swing.JFrame {

    private java.util.List<Song> songs;
    private List<Song> originalSongs;
    private String workoutType;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jTextArea1.setEnabled(true);
        workoutSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "RUNNING (120-140)", "HIIT(160-180)", "CARDIO(110-130)", "YOGA(60-80)", "WEIGHTLIFTING(130-140)", "CYCLING(130-150)", "DANCE(120-160)"
        }));
        jProgressBar1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        workoutSelectComboBox = new javax.swing.JComboBox<>();
        playlistGeneratorButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        sortAZButton = new javax.swing.JButton();
        sortDescPopularityButton = new javax.swing.JButton();
        sortUndoButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveToTxtButton = new javax.swing.JButton();
        loadFromTxtButton = new javax.swing.JButton();
        sortDescBPMButton = new javax.swing.JButton();
        sortZAButton = new javax.swing.JButton();
        sortAscPopularityButton = new javax.swing.JButton();
        sortAscBPMButton = new javax.swing.JButton();
        randomSongButton = new javax.swing.JButton();
        searchSongButton = new javax.swing.JButton();
        sortAscDurationButton = new javax.swing.JButton();
        sortDescDurationButton = new javax.swing.JButton();
        searchSongonYTButton = new javax.swing.JButton();
        selectSongToSearchOnYTButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        jProgressBar1.setForeground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 12)); // NOI18N
        jLabel1.setText("Workout Type:");

        workoutSelectComboBox.setFont(new java.awt.Font("Perpetua", 0, 12)); // NOI18N
        workoutSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        playlistGeneratorButton.setText("Generate Playlist");
        playlistGeneratorButton.setName("playlistGenerateButton"); // NOI18N
        playlistGeneratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistGeneratorButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jTextField1.setText("Playlist size...");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        sortAZButton.setText("Sort A-Z");
        sortAZButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortAZButtonActionPerformed(evt);
            }
        });

        sortDescPopularityButton.setText("Sort by Desc. Popularity");
        sortDescPopularityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortDescPopularityButtonActionPerformed(evt);
            }
        });

        sortUndoButton.setText("Undo Sorting");
        sortUndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortUndoButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveToTxtButton.setText("Save playlist to TXT");
        saveToTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToTxtButtonActionPerformed(evt);
            }
        });

        loadFromTxtButton.setText("Load from TXT");
        loadFromTxtButton.setEnabled(false);
        loadFromTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFromTxtButtonActionPerformed(evt);
            }
        });

        sortDescBPMButton.setText("Sort by Desc. BPM");
        sortDescBPMButton.setPreferredSize(new java.awt.Dimension(152, 27));
        sortDescBPMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortDescBPMButtonActionPerformed(evt);
            }
        });

        sortZAButton.setText("Sort Z-A");
        sortZAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortZAButtonActionPerformed(evt);
            }
        });

        sortAscPopularityButton.setText("Sort by Asc. Popularity");
        sortAscPopularityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortAscPopularityButtonActionPerformed(evt);
            }
        });

        sortAscBPMButton.setText("Sort by Asc. BPM");
        sortAscBPMButton.setPreferredSize(new java.awt.Dimension(152, 27));
        sortAscBPMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortAscBPMButtonActionPerformed(evt);
            }
        });

        randomSongButton.setText("Choose Random Song");
        randomSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomSongButtonActionPerformed(evt);
            }
        });

        searchSongButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchSongButton.setText("Search Song");
        searchSongButton.setName("songSearchButton"); // NOI18N
        searchSongButton.setPreferredSize(new java.awt.Dimension(120, 27));
        searchSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSongButtonActionPerformed(evt);
            }
        });

        sortAscDurationButton.setText("Sort by Asc. Duration");
        sortAscDurationButton.setMaximumSize(new java.awt.Dimension(152, 27));
        sortAscDurationButton.setMinimumSize(new java.awt.Dimension(152, 27));
        sortAscDurationButton.setPreferredSize(new java.awt.Dimension(152, 27));
        sortAscDurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortAscDurationButtonActionPerformed(evt);
            }
        });

        sortDescDurationButton.setText("Sort by Desc. Duration");
        sortDescDurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortDescDurationButtonActionPerformed(evt);
            }
        });

        searchSongonYTButton.setLabel("Search Song on YT");
        searchSongonYTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSongonYTButtonActionPerformed(evt);
            }
        });

        selectSongToSearchOnYTButton.setText("Select Song to Search on YT");
        selectSongToSearchOnYTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSongToSearchOnYTButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(workoutSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(playlistGeneratorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sortZAButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(sortDescPopularityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sortDescBPMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sortAZButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(sortAscPopularityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sortAscBPMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sortDescDurationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sortAscDurationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveToTxtButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loadFromTxtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sortUndoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(randomSongButton, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(searchSongButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchSongonYTButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectSongToSearchOnYTButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(workoutSelectComboBox)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(playlistGeneratorButton)
                        .addComponent(searchSongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortAZButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sortAscPopularityButton)
                                .addComponent(sortAscBPMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sortAscDurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveToTxtButton)
                            .addComponent(loadFromTxtButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sortDescPopularityButton)
                                .addComponent(sortDescBPMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sortZAButton)
                                .addComponent(sortDescDurationButton))
                            .addComponent(sortUndoButton)
                            .addComponent(clearButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectSongToSearchOnYTButton)
                        .addGap(8, 8, 8)
                        .addComponent(searchSongonYTButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(randomSongButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Playlist generating
    private void playlistGeneratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistGeneratorButtonActionPerformed

        workoutType = (String) workoutSelectComboBox.getSelectedItem();

        int playlistSize;

        try {
            playlistSize = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid playlist size!", "Warning", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        disableAllButtons();
        jTextArea1.setText("Loading playlist...");
        jProgressBar1.setVisible(true);
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(playlistSize);
        jProgressBar1.setValue(0);

        new Thread(new Runnable() {
            @Override
            public void run() {

                String seed = "878dadea-33c5-4c08-bdb9-e2b117475a99";

                double minTempo, maxTempo;
                switch (workoutType) {
                    case "RUNNING":
                        minTempo = 120;
                        maxTempo = 140;
                        break;
                    case "HIIT":
                        minTempo = 160;
                        maxTempo = 180;
                        break;
                    case "CARDIO":
                        minTempo = 110;
                        maxTempo = 130;
                        break;
                    case "YOGA":
                        minTempo = 60;
                        maxTempo = 80;
                        break;
                    case "WEIGHTLIFTING":
                        minTempo = 130;
                        maxTempo = 140;
                        break;
                    case "CYCLING":
                        minTempo = 130;
                        maxTempo = 150;
                        break;
                    case "DANCE":
                        minTempo = 120;
                        maxTempo = 160;
                        break;
                    default:
                        minTempo = 100;
                        maxTempo = 120;
                        break;
                }

                songs = new ArrayList<>();

                for (int i = 0; i < playlistSize; i++) {
                    double targetTempo = minTempo + Math.random() * (maxTempo - minTempo);
                    List<Song> newSongs = ApiService.getSongsByTempo(targetTempo, List.of(seed), 1);

                    if (!newSongs.isEmpty()) {
                        Song candidate = newSongs.get(0);

                        boolean duplicateSong = false;

                        for (Song s : songs) {
                            if (s.getTitle().equals(candidate.getTitle()) && s.getArtist().equals(candidate.getArtist())) {
                                duplicateSong = true;
                                break;
                            }
                        }
                        if (!duplicateSong) {
                            songs.add(candidate);

                            // progress bar 
                            final int loadingBarProgress = songs.size();
                            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                                @Override
                                public void run() {
                                    jProgressBar1.setValue(loadingBarProgress);
                                    jTextArea1.setText("Loading playlist... " + loadingBarProgress + "/" + playlistSize);
                                }
                            });
                        } else {
                            i--;
                            continue;

                        }

                    } else {
                        int choice = javax.swing.JOptionPane.showConfirmDialog(
                                null,
                                "No song found for tempo " + String.format("%.1f", targetTempo) + ". Regenerate?",
                                "Song missing",
                                javax.swing.JOptionPane.YES_NO_OPTION
                        );
                        if (choice != javax.swing.JOptionPane.YES_OPTION) {
                            break;
                        }
                        i--;
                        continue;
                    }
                }

                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        jProgressBar1.setVisible(false);
                        originalSongs = new ArrayList<>(songs);
                        jTextField1.setText("Playlist size...");
                        updateOutputArea();
                        enableAllButtons();
                    }
                });

            }
        }).start();

    }//GEN-LAST:event_playlistGeneratorButtonActionPerformed
    // Playlist size textfield
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked
    // A-Z Sort
    private void sortAZButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortAZButtonActionPerformed
        if (songs != null && !songs.isEmpty()) {
            songs.sort(new Comparator<Song>() {
                @Override
                public int compare(Song s1, Song s2) {
                    return s1.getTitle().compareToIgnoreCase(s2.getTitle());
                }
            });
            updateOutputArea();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sortAZButtonActionPerformed
    // Popularity sort Desc.
    private void sortDescPopularityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortDescPopularityButtonActionPerformed
        if (songs != null && !songs.isEmpty()) {
            songs.sort(new Comparator<Song>() {
                @Override
                public int compare(Song s1, Song s2) {
                    return Integer.compare(s2.getPopularity(), s1.getPopularity());
                }
            });
            updateOutputArea();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sortDescPopularityButtonActionPerformed
    // Undo sorting
    private void sortUndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortUndoButtonActionPerformed
        if (originalSongs == null || originalSongs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to undo!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        songs = new ArrayList<>(originalSongs);
        updateOutputArea();
    }//GEN-LAST:event_sortUndoButtonActionPerformed
    // Clear screen
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to clear!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        jTextArea1.setText("");
        songs = new ArrayList<>();
        originalSongs = new ArrayList<>();
    }//GEN-LAST:event_clearButtonActionPerformed
    // Save to TXT
    private void saveToTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToTxtButtonActionPerformed
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Nothing to save!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            savePlaylistToFile(workoutType, songs);
            javax.swing.JOptionPane.showMessageDialog(this, "Playlist saved!", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saving playlist: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveToTxtButtonActionPerformed
    /////// !Load from TXT! ////////
    private void loadFromTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFromTxtButtonActionPerformed
            /*if (workoutType == null || workoutType.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No workout type selected!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
           return;
        String filename = javax.swing.JOptionPane.showInputDialog(
            this,
            "Enter filename to load:",
            "Load Playlist",
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (filename == null || filename.isEmpty()) return; 
        try {
        String content = java.nio.file.Files.readString(java.nio.file.Path.of(filename));
        jTextArea1.setText(content);
    } catch (java.nio.file.NoSuchFileException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "File not found: " + filename, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading file: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}*/
    }//GEN-LAST:event_loadFromTxtButtonActionPerformed
    // Desc BPM sort //
    private void sortDescBPMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortDescBPMButtonActionPerformed
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        songs.sort(new Comparator<Song>() {
            @Override
            public int compare(Song s1, Song s2) {
                return Double.compare(s2.getBpm(), s1.getBpm());
            }
        });

        updateOutputArea();
    }//GEN-LAST:event_sortDescBPMButtonActionPerformed
    // Asc BPM sort //
    private void sortAscBPMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortAscBPMButtonActionPerformed
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        songs.sort(new Comparator<Song>() {
            @Override
            public int compare(Song s1, Song s2) {
                return Double.compare(s1.getBpm(), s2.getBpm());
            }
        });

        updateOutputArea();
    }//GEN-LAST:event_sortAscBPMButtonActionPerformed
    // Popularity sort Asc. // 
    private void sortAscPopularityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortAscPopularityButtonActionPerformed
        if (songs != null && !songs.isEmpty()) {
            songs.sort(new Comparator<Song>() {
                @Override
                public int compare(Song s1, Song s2) {
                    return Integer.compare(s1.getPopularity(), s2.getPopularity());
                }
            });
            updateOutputArea();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sortAscPopularityButtonActionPerformed
    // Z-A Sort
    private void sortZAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortZAButtonActionPerformed
        if (songs != null && !songs.isEmpty()) {
            songs.sort(new Comparator<Song>() {
                @Override
                public int compare(Song s1, Song s2) {
                    return s2.getTitle().compareToIgnoreCase(s1.getTitle());
                }
            });
            updateOutputArea();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sortZAButtonActionPerformed
    // Random Song
    private void randomSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomSongButtonActionPerformed
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No songs to play!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int rand = (int) (Math.random() * songs.size());
        Song randomSong = songs.get(rand);

        randomSong.play();

        javax.swing.JOptionPane.showMessageDialog(this, "Playing: \n" + randomSong.getInfo(), "Choose Random Song", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_randomSongButtonActionPerformed
    // Search Song
    private void searchSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSongButtonActionPerformed
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No songs available to search!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] searchOptions = {"BPM", "Popularity", "Artist", "Title"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this, "Search by:", "Search song", javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null, searchOptions, searchOptions[0]);

        if (choice == -1) {
            return;
        }

        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter value:");

        if (input == null || input.isEmpty()) {
            return;
        }

        List<Song> found = new ArrayList<>();

        switch (choice) {
            case 0: // BPM
                try {
                    double bpm = Double.parseDouble(input);
                    for (Song s : songs) {
                        if ((int) Math.round(s.getBpm()) == (int) Math.round(bpm)) {
                            found.add(s);
                        }
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid BPM value!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                break;

            case 1: // Popularity
                try {
                    int pop = Integer.parseInt(input);
                    for (Song s : songs) {
                        if (s.getPopularity() == pop) {
                            found.add(s);
                        }
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid popularity value!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                break;

            case 2: // Artist
                for (Song s : songs) {
                    if (s.getArtist().equalsIgnoreCase(input)) {
                        found.add(s);
                    }
                }
                break;

            case 3: // Title
                for (Song s : songs) {
                    if (s.getTitle().equalsIgnoreCase(input)) {
                        found.add(s);
                    }
                }
                break;

            default:
                return;
        }

        if (found.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No songs found!", "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            String text = "=== Search Results ===\n\n";
            for (Song s : found) {
                text = text + s.getInfo() + "\n";
            }
            javax.swing.JOptionPane.showMessageDialog(this, text, "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_searchSongButtonActionPerformed
    // Asc duration sort
    private void sortAscDurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortAscDurationButtonActionPerformed
        if (songs != null && !songs.isEmpty()) {
            songs.sort(new Comparator<Song>() {
                @Override
                public int compare(Song s1, Song s2) {
                    return Double.compare(s1.getDuration(), s2.getDuration());
                }
            });
            updateOutputArea();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sortAscDurationButtonActionPerformed
    // Desc duration sort
    private void sortDescDurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortDescDurationButtonActionPerformed
        if (songs != null && !songs.isEmpty()) {
            songs.sort(new Comparator<Song>() {
                @Override
                public int compare(Song s1, Song s2) {
                    return Double.compare(s2.getDuration(), s1.getDuration());
                }
            });
            updateOutputArea();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to sort!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sortDescDurationButtonActionPerformed

    private Song selectedSong = null;
    private void chooseSongFromPlaylist() {
        if (songs == null || songs.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No songs available!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] songOptions = new String[songs.size()];
        for (int i = 0; i < songs.size(); i++) {
            songOptions[i] = songs.get(i).getTitle() + " - " + songs.get(i).getArtist();
        }

        String selectedSongStr = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Select a song:",
                "Choose Song",
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                null,
                songOptions,
                songOptions[0]
        );

        if (selectedSongStr != null) {
            // Megkeressük a kiválasztott Song objektumot
            for (Song s : songs) {
                if ((s.getTitle() + " - " + s.getArtist()).equals(selectedSongStr)) {
                    selectedSong = s; // itt állítjuk be a kiválasztott dalt
                    javax.swing.JOptionPane.showMessageDialog(this, "Selected: " + selectedSong.getInfo());
                    break;
                }
            }
        }
    }

    //Search Song on YT
    private void searchSongonYTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSongonYTButtonActionPerformed
        if (selectedSong == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a song first!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = selectedSong.getTitle() + " " + selectedSong.getArtist();
        query = query.replace(" ", "+"); // URL friendly

        String url = "https://www.youtube.com/results?search_query=" + query;

        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Could not open browser: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchSongonYTButtonActionPerformed

    private void selectSongToSearchOnYTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSongToSearchOnYTButtonActionPerformed
        chooseSongFromPlaylist();
    }//GEN-LAST:event_selectSongToSearchOnYTButtonActionPerformed
    // Disable buttons
    private void disableAllButtons() {
        playlistGeneratorButton.setEnabled(false);
        sortAZButton.setEnabled(false);
        sortDescPopularityButton.setEnabled(false);
        sortUndoButton.setEnabled(false);
        clearButton.setEnabled(false);
        saveToTxtButton.setEnabled(false);
        loadFromTxtButton.setEnabled(false);
        sortDescBPMButton.setEnabled(false);
        sortZAButton.setEnabled(false);
        sortAscPopularityButton.setEnabled(false);
        sortAscBPMButton.setEnabled(false);
        randomSongButton.setEnabled(false);
        searchSongButton.setEnabled(false);
        sortAscDurationButton.setEnabled(false);
        sortDescDurationButton.setEnabled(false);
        jTextField1.setEnabled(false);
        workoutSelectComboBox.setEnabled(false);
        searchSongonYTButton.setEnabled(false);
        selectSongToSearchOnYTButton.setEnabled(false);
    }

    // Enable buttons
    private void enableAllButtons() {
        playlistGeneratorButton.setEnabled(true);
        sortAZButton.setEnabled(true);
        sortDescPopularityButton.setEnabled(true);
        sortUndoButton.setEnabled(true);
        clearButton.setEnabled(true);
        saveToTxtButton.setEnabled(true);
        sortDescBPMButton.setEnabled(true);
        sortZAButton.setEnabled(true);
        sortAscPopularityButton.setEnabled(true);
        sortAscBPMButton.setEnabled(true);
        randomSongButton.setEnabled(true);
        searchSongButton.setEnabled(true);
        sortAscDurationButton.setEnabled(true);
        sortDescDurationButton.setEnabled(true);
        jTextField1.setEnabled(true);
        workoutSelectComboBox.setEnabled(true);
        searchSongonYTButton.setEnabled(true);
        selectSongToSearchOnYTButton.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    // Output update //
    private void updateOutputArea() {
        String text = "=== " + workoutType + " Playlist ===\n\n";
        for (int i = 0; i < songs.size(); i++) {
            text = text + " - " + songs.get(i).getInfo() + "\n";
        }
        text += "\nTotal songs: " + songs.size();
        jTextArea1.setText(text);
        jTextArea1.setCaretPosition(0);

    }

    // Save playlist to TXT
    private void savePlaylistToFile(String workoutType, List<Song> songs) throws Exception {
        if (songs == null || songs.isEmpty()) {
            return;
        }

        String filename = workoutType + "_playlist.txt";

        String text = "=== " + workoutType + " Playlist ===\n\n";

        for (int i = 0; i < songs.size(); i++) {
            text = text + " - " + songs.get(i).getInfo() + "\n";
        }

        Files.write(Path.of(filename), text.getBytes());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loadFromTxtButton;
    private javax.swing.JButton playlistGeneratorButton;
    private javax.swing.JButton randomSongButton;
    private javax.swing.JButton saveToTxtButton;
    private javax.swing.JButton searchSongButton;
    private javax.swing.JButton searchSongonYTButton;
    private javax.swing.JButton selectSongToSearchOnYTButton;
    private javax.swing.JButton sortAZButton;
    private javax.swing.JButton sortAscBPMButton;
    private javax.swing.JButton sortAscDurationButton;
    private javax.swing.JButton sortAscPopularityButton;
    private javax.swing.JButton sortDescBPMButton;
    private javax.swing.JButton sortDescDurationButton;
    private javax.swing.JButton sortDescPopularityButton;
    private javax.swing.JButton sortUndoButton;
    private javax.swing.JButton sortZAButton;
    private javax.swing.JComboBox<String> workoutSelectComboBox;
    // End of variables declaration//GEN-END:variables
}
